In [30]:
%load_ext autoreload
%autoreload 2
import numpy as np
from sys import path
path.insert(0, '..')
from scripts.gaussian_classifiers import train_Gaussian_multivariate, get_priors,get_predictions_Gaussian_Mult,train_Gaussian_Naive_Bayes,train_Gaussian_TiedCovariance
from scripts.utility import vCol,map_labels_into_numbers
import scipy
import json
import pandas as pd

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
D=np.load('../data/processed/D_train_latent.npy')
L=np.load('../data/processed/L_train.npy')
labels_to_num=json.load(open('../data/processed/labels_to_num.json','r'))
num_to_labels=json.load(open('../data/processed/num_to_label.json','r'))
D_test=np.load('../data/processed/D_test.npy')
L_test=np.load('../data/processed/L_test.npy')

In [9]:
parameters_GM=train_Gaussian_multivariate(D,L)
parameters_GM

[(array([ 8.6098215 ,  4.96914758,  0.11620267, -0.03863962,  0.10905651]),
  array([[ 0.99346994, -0.03491033, -0.04778424, -0.16714719,  0.08514415],
         [-0.03491033,  1.5662199 ,  0.20140436, -0.17122591,  0.09922466],
         [-0.04778424,  0.20140436,  0.6155012 , -0.26565616, -0.01167607],
         [-0.16714719, -0.17122591, -0.26565616,  0.4872795 , -0.11943682],
         [ 0.08514415,  0.09922466, -0.01167607, -0.11943682,  0.92148209]])),
 (array([ 3.8904529 , -3.30567153, -0.18566893,  0.0177144 , -0.94231855]),
  array([[ 1.69076443,  1.2369185 , -0.20481568,  0.01669297, -0.39993609],
         [ 1.2369185 ,  2.62272412,  0.12376671,  0.04284894, -0.3762017 ],
         [-0.20481568,  0.12376671,  0.37395646, -0.17993037,  0.07212926],
         [ 0.01669297,  0.04284894, -0.17993037,  0.50867286,  0.05129867],
         [-0.39993609, -0.3762017 ,  0.07212926,  0.05129867,  1.60461869]])),
 (array([ 3.24599615, -4.54004442, -0.16570008, -0.02201025,  0.76745731]),
  arra

In [10]:
priors=get_priors(D,L)
np.save('../data/processed/priors.npy',priors)
priors

[0.1913764961915125,
 0.1749183895538629,
 0.1868879216539717,
 0.16675734494015235,
 0.13411316648531013,
 0.1459466811751904]

In [23]:
predictions=get_predictions_Gaussian_Mult(D_test,L_test,parameters_GM,priors)
acc=np.where(predictions==L_test,1,0).mean()
print(f"The accuracy of Gaussian Multivariate is : {acc*100}%")

The accuracy of Gaussian Multivariate is : 85.20529351883272%


In [24]:
print("The label predicted is:")
for p in predictions:
    print(f"{num_to_labels[f"{p}"]}")

The label predicted is:
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
SITTING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
SITTING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
STANDING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
LAYING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING
WALKING_DOWNSTAIRS
WALKING_DOWNSTAIRS
WALKING_DOWNSTAIRS
WALKING_DOWNSTAIRS

In [29]:
parameters_NB=train_Gaussian_Naive_Bayes(D,L)
predictions=get_predictions_Gaussian_Mult(D_test,L_test,parameters_NB,priors)
acc=np.where(predictions==L_test,1,0).mean()
print(f"The accuracy of Gaussian Naive Bayes is : {acc*100}%")

The accuracy of Gaussian Naive Bayes is : 85.3070919579233%


In [31]:
parameters_TD=train_Gaussian_TiedCovariance(D,L)
predictions=get_predictions_Gaussian_Mult(D_test,L_test,parameters_TD,priors)
acc=np.where(predictions==L_test,1,0).mean()
print(f"The accuracy of Gaussian Tied Covariance is : {acc*100}%")

The accuracy of Gaussian Tied Covariance is : 86.90193417034273%
